on:
  workflow_dispatch

jobs:
  run-node-script:
    runs-on: ubuntu-latest

    steps:
    - name: Print variable
      run: echo "$CI"

    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: "24.x"

    - name: ls
      run: ls

    - name: Print variable
      run: node index.ts
